title: "DBSCAN: Density-Based Spatial Clustering of Applications with Noise, Technique Exploration"
description: "Exploring DBSCAN for clustering and outlier detection"
markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax
  math_engine_opts:
    delimiters:
      inline: ["$", "$"]    # Use $ for inline math
      block: ["$$", "$$"]   # Use $$ for block math
plugins:
  - jekyll-mathjax

# Exclude unnecessary files from GitHub Pages build
exclude:
  - "*.Rhistory"
  - "*.Rapp.history"
  - "*.RData"
  - "*.tar.gz"
  - "*.Rcheck/"
  - ".gitignore"
  - ".gitattributes"
  - "cache/"
  - "vignettes/*.html"
  - "vignettes/*.pdf"

# Include essential directories
include:
  - docs
  - Clustering_files/figure-gfm
  - images

# Set the home page to clustering.md instead of index.md
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
      permalink: "/"
